services:
  gatsby:
    build:
      context: .
      dockerfile: Dockerfile.simple
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=${SERVER_NAME:-vlima.in}
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - gatsby-network

networks:
  gatsby-network:
    driver: bridge 