name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Gatsby site
      run: npm run build
      env:
        GATSBY_GA_MEASUREMENT_ID: ${{ secrets.GATSBY_GA_MEASUREMENT_ID }}
        
    - name: Deploy to VPS
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          cd ${{ secrets.VPS_PROJECT_PATH }}
          git pull origin main
          
          # Create .env file with environment variables
          echo "GATSBY_GA_MEASUREMENT_ID=${{ secrets.GATSBY_GA_MEASUREMENT_ID }}" > .env
          echo "SERVER_NAME=${{ secrets.SERVER_NAME }}" >> .env
          
          # Run deployment script
          chmod +x deploy.sh
          ./deploy.sh
          
          # Clean up old Docker images to save space
          docker image prune -f
          
    - name: Notify deployment status
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment to VPS completed successfully!"
        else
          echo "❌ Deployment to VPS failed!"
        fi
