name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        timeout: 60s
        command_timeout: 15m
        script: |
          cd ${{ secrets.VPS_PROJECT_PATH }}
          
          # Pull latest changes
          git pull origin main
          
          # Create environment file
          echo "GATSBY_GA_MEASUREMENT_ID=${{ secrets.GATSBY_GA_MEASUREMENT_ID }}" > .env
          echo "SERVER_NAME=${{ secrets.SERVER_NAME }}" >> .env
          
          # Restore SSL certificates
          mkdir -p nginx/ssl
          echo "${{ secrets.SSL_FULLCHAIN }}" > nginx/ssl/fullchain.pem
          echo "${{ secrets.SSL_PRIVKEY }}" > nginx/ssl/privkey.pem
          chmod 644 nginx/ssl/fullchain.pem
          chmod 600 nginx/ssl/privkey.pem
          
          # Deploy
          chmod +x deploy.sh
          ./deploy.sh
          
          # Cleanup
          docker image prune -f
          
    - name: Notify deployment status
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment to VPS completed successfully!"
        else
          echo "❌ Deployment to VPS failed!"
        fi
